### ISSUE TITLE
Amount should be decimal instead of int

### ISSUE THREAD

**Issue by ndoubismarck** [zmxv/bitmexgo#2]
Amount should be `decimal.NewFromFloat(amount)` instead of `int` see https://github.com/shopspring/decimal

https://github.com/zmxv/bitmexgo/blob/1eb5bbacf62a07e6fddba28c14c16dcba280497f/api_user.go#L1692

Refer to https://www.bitmex.com/api/explorer/#!/User/User_requestWithdrawal

**Comment by zmxv** [comment]
The original type of `amount` was `float32`, but in practice you should always pass in an integral value because the implicit unit is satoshi here and a fractional satoshi makes no sense.
To save us the trouble of explicit type coercion, I changed `amount`'s type to `int`.

This is working as intended and verified in production.

**Comment by ndoubismarck** [comment]
Ok that's clear enough
